version: '3.9'
services:
  Chiru: 
    profiles: ["no-proxy"]
    container_name: Chiru
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - OPENAI_API_KEY=sk-nowm8nqM1OQLGQUd3600F6340fEd4560A882217cE7Ef91Ce
      - CODE=yifan
      - BASE_URL=https://api.mctools.online
      - OPENAI_ORG_ID=$OPENAI_ORG_ID
      - HIDE_USER_API_KEY=$HIDE_USER_API_KEY
      - DISABLE_GPT4=$DISABLE_GPT4
